# action.yml
name: 'Batch Schema Publisher'
description: 'Publish your schemas to the Batch platform'
inputs:
  schema_id:
    description: 'Batch schema ID'
    required: true

  schema_type:
    description: 'Type of schemas we are working with'
    required: true
    default: 'protobuf'

  schema_name:
    description: 'Naming format to use for newly published schemas'
    required: true

  api_token:
    description: 'Batch API token'
    required: true

  root_dir:
    description: 'If using artifact_type=protos_archive, specify the directory that contains schemas and should be treated as root'
    required: false
    default: './'

  api_address:
    description: 'HTTP address for the Batch API'
    required: false
    default: 'https://api.batch.sh'

  debug:
    description: 'Enable debug output'
    required: false
    default: 'false'

  artifact_type:
    description: 'Type of artifact to upload. Either: protos_archive or descriptor_set'
    required: false
    default: "protos_archive"

  descriptor_set_path:
    description: 'If using artifact_type=descriptor_set, specify the path to the .fds/.protoset file to upload'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    BATCH_SCHEMA_ID: ${{ inputs.schema_id }}
    BATCH_SCHEMA_TYPE: ${{ inputs.schema_type }}
    BATCH_SCHEMA_NAME: ${{ inputs.schema_name }}
    BATCH_API_TOKEN: ${{ inputs.api_token }}
    BATCH_ROOT_DIR: ${{ inputs.root_dir }}
    BATCH_API_ADDRESS: ${{ inputs.api_address }}
    DEBUG: ${{ inputs.debug }}
